// One quote per challenge day (75). Attributed only where the source is well established.
const GENERAL = [
  ['We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Will Durant'],
  ['Discipline equals freedom.', 'Jocko Willink'],
  ['What stands in the way becomes the way.', 'Marcus Aurelius'],
  ['No one is coming to save you. Good. Get up.'],
  ['It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca'],
  ['First say to yourself what you would be; then do what you have to do.', 'Epictetus'],
  ['Motivation gets you started. Systems get you finished.'],
  ['Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius'],
  ['You do not rise to the level of your goals. You fall to the level of your systems.', 'James Clear'],
  ['Today\'s discomfort is tomorrow\'s capability.'],
  ['We suffer more often in imagination than in reality.', 'Seneca'],
  ['Be so consistent that quitting stops being an option.'],
  ['No man is free who is not master of himself.', 'Epictetus'],
  ['The standard you walk past is the standard you accept.'],
  ['Do the work. Let the results be loud.'],
  ['Nobody cares. Work harder.'],
  ['Small hinges swing big doors.'],
  ['You are one disciplined season away from a different life.'],
  ['Comfort is a slow way to lose.'],
  ['Don\'t negotiate with the alarm. Obey it.'],
  ['The day is won in the first hour and kept in the last.'],
  ['Quiet work compounds loudly.'],
  ['Be the person your future self thanks.'],
  ['Hard days are the entrance fee for a good life.'],
  ['A calm mind does the best work.'],
  ['Make today boringly excellent.'],
  ['Your habits are voting for the person you become.', 'James Clear'],
  ['Strength is built in the reps nobody watches.'],
  ['Stop waiting to feel ready. Start.'],
  ['Protect your sleep, your focus and your word.'],
  ['Every rep, every page, every hour: it adds up.'],
  ['Win the morning, win the day.'],
  ['You don\'t need more time. You need fewer excuses.'],
  ['Pressure is a privilege. It means the work matters.'],
  ['Choose the harder right over the easier wrong.'],
  ['Energy follows action.'],
  ['What you do daily matters more than what you do occasionally.'],
  ['Discipline is remembering what you want.'],
  ['The only bad workout is the one that didn\'t happen.'],
  ['Be ruthless about your time and generous with your effort.'],
  ['Clarity comes from engagement, not thought.'],
  ['Eat clean. Sleep early. Train hard. Repeat.'],
  ['Focus is a muscle. Train it in silence.'],
  ['Trade comfort for growth, one hour at a time.'],
  ['Your future is built by what you do right now.'],
  ['Slow is smooth. Smooth is fast.'],
  ['Progress, not perfection. But progress every single day.'],
  ['The version of you that you want is on the other side of this day.'],
  ['Self-respect is the reward of keeping promises to yourself.'],
  ['Don\'t count the days. Make the days count.'],
  ['Stay hungry for the work, patient for the result.'],
  ['The grind is the glamour you can\'t see yet.'],
  ['One more rep. One more page. One more hour.'],
  ['Tired is not the same as done.'],
  ['Ordinary effort, extraordinary consistency.'],
  ['Build the life you don\'t need a vacation from.'],
  ['The work you avoid is usually the work that matters.'],
  ['Show up when it\'s dull. That\'s where it\'s decided.'],
  ['Great things are done by a series of small things brought together.'],
  ['Mood is optional. Execution isn\'t.'],
  ['You are building proof that your word means something.'],
  ['Keep the promise. Keep the streak. Keep going.'],
  ['You said you would. Now do.'],
  ['Sweat now, shine later.'],
  ['Your only competition is who you were yesterday.'],
  ['Consistency is the quiet superpower.'],
  ['Do it tired. Do it bored. Do it anyway.'],
  ['Great lives are built in unglamorous hours.'],
  ['Hold the line.'],
];

// Quotes tied to a specific point in the 75-day arc.
const PINNED = {
  1: ['Well begun is half done.'],
  38: ['Halfway is where most people quit. Stay.'],
  45: ['The old you is watching. Don\'t go back.'],
  55: ['The last 20 days are why you started.'],
  60: ['A few more weeks of discipline for a lifetime of options.'],
  65: ['Ten more days. Make them your best ten.'],
  70: ['Don\'t coast to the line. Sprint through it.'],
  74: ['Finish strong. Strong finishes are remembered.'],
  75: ['Last day. Win it like the first.'],
};

export function quoteFor(dayNo, key) {
  if (PINNED[dayNo]) return PINNED[dayNo];
  if (dayNo >= 1 && dayNo <= 75) {
    // Skip the pinned days so the general pool is used without repeats.
    const idx = dayNo - 1 - Object.keys(PINNED).filter((d) => +d < dayNo).length;
    return GENERAL[idx % GENERAL.length];
  }
  const h = Math.abs([...key].reduce((a, c) => a * 31 + c.charCodeAt(0), 7));
  return GENERAL[h % GENERAL.length];
}
